### PR TITLE
Update driveitem-delta.md of driveItem delta for deltaExcludeParent h…

### PR DESCRIPTION
**Pull request by MahaGoyal**
…eader.

**Instructions:** _Add any supporting information, such as a description of the PR changes, here._

---
> [!NOTE]
> The following guidance is for Microsoft employees only. Community contributors can ignore this message; our content team will manage the status.
<details><summary><i>After you've created your PR</i>, expand this section for tips and additional instructions.</summary>

- **do not merge** is the default PR status and is automatically added to all open PRs that don't have the **ready to merge** label.
- Add the **ready for content review** label to start a review. Your PR won't be reviewed until you add this label.
- If your content reviewer requests changes, review the feedback and address accordingly as soon as possible to keep your pull request moving forward. After you address the feedback, remove the **changes requested** label, add the **review feedback addressed** label, and select the **Re-request review** icon next to the content reviewer's alias. If you can't add labels, add a comment with `#feedback-addressed` to the pull request.
- After the content review is complete, your reviewer will add the **content review complete** label. When the updates in this PR are ready for external customers to use, replace the **do not merge** label with **ready to merge** and the PR will be merged within 24 working hours.
- Pull requests that are inactive for more than 6 weeks will be automatically closed. Before that, you receive reminders at 2 weeks, 4 weeks, and 6 weeks. If you still need the PR, you can reopen or recreate the request.

For more information, see the [Content review process summary](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/614263/Content-workflow).

</details>

### CODE REVIEW

**Comment by MartinM85** [comment]
Seems like the correct header is `Prefer: deltaExcludeParent`

**Comment by aiai287** [comment]
Is this workable on direct REST API call?

I tried to call GET /me/drive/root/delta in my code and graph explorer with

header

Prefer: deltaExcludeParent and deltaExcludeParent: true

both not works


can anyone help me? thanks

**Comment by MartinM85** [comment]
From my experience, `Prefer: deltaExcludeParent` is ignored in the first call

    GET /me/drive/root/delta

But subsequent calls with token GET /me/drive/root/delta?token=xxx should take the header `Prefer: deltaExcludeParent` in account

**Comment by aiai287** [comment]
@MartinM85, I have tested it's working on organization account but not working on personal account. I using the header `Prefer: deltaExcludeParent`.

**Pull request merged**
