### PR TITLE
Update group-list-members-permissions.md

### PR DESCRIPTION
**Pull request by himani-chi**
One needs 'User.Read.All' to read all the AdditionalProperties from 'Get-MgGroupMember'. Lack of this permission would result in returning only two properties - 'businessPhones' (with empty value) and '@odata.type'.

**Instructions:** _Add any supporting information, such as a description of the PR changes, here._

---
> [!NOTE]
> The following guidance is for Microsoft employees only. Community contributors can ignore this message; our content team will manage the status.
<details><summary><i>After you've created your PR</i>, expand this section for tips and additional instructions.</summary>

- **do not merge** is the default PR status and is automatically added to all open PRs that don't have the **ready to merge** label.
- Add the **ready for content review** label to start a review. Your PR won't be reviewed until you add this label.
- If your content reviewer requests changes, review the feedback and address accordingly as soon as possible to keep your pull request moving forward. After you address the feedback, remove the **changes requested** label, add the **review feedback addressed** label, and select the **Re-request review** icon next to the content reviewer's alias. If you can't add labels, add a comment with `#feedback-addressed` to the pull request.
- After the content review is complete, your reviewer will add the **content review complete** label. When the updates in this PR are ready for external customers to use, replace the **do not merge** label with **ready to merge** and the PR will be merged within 24 working hours.
- Pull requests that are inactive for more than 6 weeks will be automatically closed. Before that, you receive reminders at 2 weeks, 4 weeks, and 6 weeks. If you still need the PR, you can reopen or recreate the request.

For more information, see the [Content review process summary](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/614263/Content-workflow).

</details>

### CODE REVIEW

**Review by timayabi2020 — APPROVED** [review]

**Comment by Lauragra** [comment]
Submitted internal PR for this change. Waiting for approval.

**Comment by Lauragra** [comment]
@FaithOmbongi , FYI, I submitted PR 22961 per this PR but it hasn't yet been approved.

**Review by FaithOmbongi — COMMENTED** [review]
Thank you @himani-chi for proposing this change.

[The article that references this permissions file](https://learn.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&tabs=http#permissions) includes a note after the permissions table explaining the limited information that's returned, to address the gap you're attempting to close.

image

Please note that this behavior affects all directory objects. So, if using only the least privilege permission:
- Users will additionally need User.Read.All to read all the info, otherwise, you see the basic user info.
- Devices will additionally need Device.Read.All to read all the info, otherwise, you see the basic device info.
- Same case for service principals, contacts, and groups.

Therefore, adding User.Read.All only doesn't meet the needs for the other 4 object types that can be members.

Please let me know if this feedback helps clarify why we can't apply the proposed change for now.

**Comment by FaithOmbongi** [comment]
Hi @himani-chi - I haven't heard back from you, but I hope my feedback was satisfactory. I'll proceed to close this PR but if you still have questions, feel free to reopen the PR or ping me internally. Thanks and looking forward to more of your contributions.

**Comment by FaithOmbongi** [comment]
Hi @himani-chi - I haven't heard back from you, but I hope my feedback was satisfactory. I'll proceed to close this PR but if you still have questions, feel free to reopen the PR or ping me internally. Thanks and looking forward to more of your contributions.

**Pull request closed without merging**
